/**
 * OpenAPI Stuff API created to reproduce issue
 * Example created
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.zapodot.openapi.models

import jakarta.validation.constraints.*
import jakarta.validation.Valid
import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 *
 * @param name 
 * @param id 
 * @param tag 
 */


data class Stuff (


    @JsonProperty("name")
    @field:Valid
    @field:NotNull
    val name: kotlin.String,


    @JsonProperty("id")
    @field:Valid
    val id: kotlin.Long? = null,


    @JsonProperty("tag")
    @field:Valid
    val tag: kotlin.String? = null

)

